- name: example ec2 vpc
  ec2_vpc_net:
    name: devnet
    cidr_block: 10.10.0.0/16
    region: us-west-2
    state: present

- name: example ec2 group
  ec2_group:
    name: devgroup
    description: Dev EC2 group
    vpc_id: vpc-4a7f962d
    region: us-west-2
    rules:
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0


